export const DEFAULT_TIPS: string[] = [
  "Consejo: A veces es mejor crear un arma nueva que repararla, sobre todo de inicio.",
  "Consejo: Coloca trampas alrededor de tu base para frenar hordas.",
  "Consejo: Usa el arco al principio, es barato y silencioso.",
  "Consejo: Explora ciudades para lootear mejores armas.",
  "Consejo: Acuerdate de comer y beber. Sino morirás",
  "Consejo: Recuerda ir a explorar diferentes biomas",
  "Consejo: Los caramelos destruyeroca son exquisitos",
  "Consejo: Mina con cuidado en el desierto",
  "Consejo: Un Cafe siempre viene bien",
  "Consejo: Si escuchas un gruñido, corre o prepárate para pelear",
  "Consejo: Las minas pueden ser tu mejor amigo o tu peor enemigo, úsalas sabiamente",
  "Consejo: Siempre lleva kits de reparacion",
  "Consejo: Recuerda llevar siempre algo para curarte",
  "Consejo: El día 7 no es el problema. El problema eres tú sin café",
  "Consejo: La base perfecta no existe… pero la tuya casi",
  "Consejo: Hoy farmeas, mañana sobrevives",
  "Consejo: Un bloque mal puesto puede ser tu final",
  "Consejo: En este reino no se sobrevive: se disfruta",
  "Consejo: Aquí cada wipe es una aventura y cada noche una historia",
  "Consejo: No mires atrás. Si algo te sigue, ya lo oirás",
  "Consejo: Una buena base salva vidas. Una mala base hace clips",
  "Consejo: Si no refuerzas hoy, lloras mañana",
  "Consejo: El ruido atrae zombis, pero también atrae diversión",
  "Consejo: Cada ciudad es un riesgo, cada casa una historia",
  "Consejo: El mapa es grande, pero tu mochila no",
  "Consejo: Explorar es fácil. Volver vivo es la parte complicada",
  "Consejo: Cada wipe es un renacer… y esta vez vamos con más ganas",
  "Consejo: Primer día, cero loot, mil peligros. Perfecto",
  "Consejo: Todo vale oro: madera, piedra, comida, agua, huesos, latas…",
  "Consejo: Revisa coches, basura, mochilas, buzones...",
  "Consejo: Si estás empezando, muévete con calma y evita peleas grandes",
  "Consejo: La bici es barata y te cambia la vida",
  "Consejo: Al principio, por la noche: Quédate en casa, no hagas ruido, craftea, cocina y organiza el inventario",
];
